apiVersion: batch/v1
kind: Job
metadata:
  name: secret-init
  namespace: backend
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccountName: backend
      restartPolicy: OnFailure
      containers:
        - name: secret-init
          image: busybox
          command: ["sh", "-c", "ls /mnt/secrets && echo secrets mounted successfully"]
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets
              readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: backend-secrets
